stages:
  - deploy
  - verify

variables:
  KUBECONFIG: /root/.kube/config
  FISSION_URL: http://localhost:9090

deploy-fission-specs:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache curl bash
    - echo "Downloading Fission CLI..."
    - curl -Lo fission https://github.com/fission/fission/releases/download/v1.21.0/fission-v1.21.0-linux-amd64
    - chmod +x fission && mv fission /usr/local/bin/

    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_DATA" > ~/.kube/config
    - chmod 600 ~/.kube/config
    - cd backend

    # Automatically compress each module
    - echo "Zipping mharvester..."
    - cd mharvester && chmod +x build.sh && zip -r mharvest.zip . && mv mharvest.zip ../ && cd ..
    - echo "Zipping rharvester..."
    - cd rharvester && chmod +x build.sh && zip -r rharvest.zip . && mv rharvest.zip ../ && cd ..

    - echo "Zipping subredditstats..."
    - cd subredditdata && chmod +x build.sh && zip -r subredditstats.zip . && mv subredditstats.zip ../ && cd ..
    - echo "Cleaning up previous route (if exists)..."
    - KUBECONFIG=~/.kube/config fission httptrigger delete --name subredditstats || true

    - echo "Validating specs..."
    - KUBECONFIG=~/.kube/config fission spec validate --specdir specs
    - echo "Applying specs..."
    - KUBECONFIG=~/.kube/config fission spec apply --specdir specs --wait

verify-es-ingest:
  stage: verify
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    - echo "Skipping ES check in CI — not inside K8s cluster"
    - curl -s https://elasticsearch-master.elastic.svc.cluster.local:9200/mastodon-posts/_count || true

test-fission-functions:
  stage: verify
  image: alpine:latest
  script:
    - apk add --no-cache curl bash
    - echo "Downloading Fission CLI..."
    - curl -Lo fission https://github.com/fission/fission/releases/download/v1.21.0/fission-v1.21.0-linux-amd64
    - chmod +x fission && mv fission /usr/local/bin/

    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_DATA" > ~/.kube/config
    - chmod 600 ~/.kube/config

    - echo "Testing functions internally..."
    - KUBECONFIG=~/.kube/config fission function test --name mharvest
    - KUBECONFIG=~/.kube/config fission function test --name rharvest

