stages:
  - deploy
  - verify

variables:
  KUBECONFIG: /root/.kube/config
  FISSION_URL: http://localhost:9090

before_script:
  - mkdir -p ~/.kube
  - echo "$KUBECONFIG_DATA" > ~/.kube/config
  - chmod 600 ~/.kube/config

deploy-fission-specs:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache curl bash zip
    - echo "Downloading Fission CLI..."
    - curl -Lo fission https://github.com/fission/fission/releases/download/v1.21.0/fission-v1.21.0-linux-amd64
    - chmod +x fission && mv fission /usr/local/bin/
    
    - cd backend

    # Automatically compress each module
    - echo "Zipping mharvester..."
    - cd mharvester && chmod +x build.sh && zip -r mharvest.zip . && mv mharvest.zip ../ && cd ..
    - echo "Zipping rharvester..."
    - cd rharvester && chmod +x build.sh && zip -r rharvest.zip . && mv rharvest.zip ../ && cd ..
    - echo "Zipping subredditstats..."
    - cd subredditdata && chmod +x build.sh && zip -r subredditstats.zip . && mv subredditstats.zip ../ && cd ..
    - echo "Zipping mastodon_esdata..."
    - cd mdata && chmod +x build.sh && zip -r mstats.zip . && mv mstats.zip ../ && cd ..
    - echo "Zipping reddit_esdata..."
    - cd rdata && chmod +x build.sh && zip -r rstats.zip . && mv rstats.zip ../ && cd ..
    - echo "Zipping mastodon_timeseries_analyze..."
    - cd timeseries && chmod +x build.sh && zip -r timestats.zip . && mv timestats.zip ../ && cd ..
    - echo "Zipping mastodon_content..."
    - cd content && chmod +x build.sh && zip -r mcontent.zip . && mv mcontent.zip ../ && cd ..

    - fission httptrigger delete --name subredditstats || true
    - fission httptrigger delete --name stats-reddit-date-keyword-trigger || true
    - fission httptrigger delete --name stats-reddit-keyword-trigger || true
    - fission httptrigger delete --name stats-reddit-date-trigger || true
    - fission httptrigger delete --name stats-mastodon-date-keyword-trigger || true
    - fission httptrigger delete --name stats-mastodon-keyword-trigger || true
    - fission httptrigger delete --name stats-mastodon-date-trigger || true
    - fission httptrigger delete --name stats-mastodon-header-trigger || true
    - fission httptrigger delete --name stats-reddit-header-trigger || true
    - fission httptrigger delete --name stats-mastodon-timeseries-trigger || true
    - fission httptrigger delete --name content-mastodon-header-trigger || true

    - echo "Validating specs..."
    - KUBECONFIG=~/.kube/config fission spec validate
    - echo "Applying specs..."
    - KUBECONFIG=~/.kube/config fission spec apply --specdir specs --wait

verify-es-ingest:
  stage: verify
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    - echo "Skipping ES check in CI — not inside K8s cluster"
    - curl -s https://elasticsearch-master.elastic.svc.cluster.local:9200/mastodon-posts/_count || true

check-fission-functions:
  stage: verify
  image: alpine:latest
  variables:
    FISSION_URL: "http://127.0.0.1:9090"
  script:
    - apk add --no-cache curl bash jq
    - echo "Downloading Fission CLI..."
    - curl -Lo fission https://github.com/fission/fission/releases/download/v1.21.0/fission-v1.21.0-linux-amd64
    - chmod +x fission && mv fission /usr/local/bin/

    - echo "Checking if function is deployed..."
    - KUBECONFIG=~/.kube/config fission function get --name mharvest || echo "mharvest not found"
    - KUBECONFIG=~/.kube/config fission function get --name rharvest || echo "rharvest not found"


