stages:
  - deploy
  - verify

variables:
  KUBECONFIG: /root/.kube/config
  FISSION_URL: http://localhost:9090

deploy-fission-specs:
  stage: deploy
  image: fission/fission-cli
  script:
    - cd backend
    - fission spec validate
    - fission spec apply --specdir specs --wait

verify-es-ingest:
  stage: verify
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    - curl -s https://elasticsearch-master.elastic.svc.cluster.local:9200/mastodon-posts/_count | jq .
    - curl -s https://elasticsearch-master.elastic.svc.cluster.local:9200/reddit-posts/_count | jq .

test-fission-functions:
  stage: verify
  image: alpine:latest
  variables:
    FISSION_URL: "http://127.0.0.1:9090"
  script:
    - apk add --no-cache curl jq
    - curl -s -X POST "$FISSION_URL/mharvest" | jq .
    - curl -s -X POST "$FISSION_URL/rharvest" | jq .

