
apiVersion: batch/v1
kind: Job
metadata:
  name: pharvest-job
spec:
  template:
    spec:
      containers:
      - name: pharvest
        image: python:3.10-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install decorator==5.1.1 Mastodon.py==2.0.1 flask==2.2.5 elasticsearch8==8.11.1 vaderSentiment==3.3.2 && python /app/pharvest.py
        volumeMounts:
        - name: script-volume
          mountPath: /app
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: pharvest-script
