apiVersion: fission.io/v1
kind: Package
metadata:
  name: stats
spec:
  environment:
    name: python39

  source:
    type: git
    url: "https://gitlab.unimelb.edu.au/HENGJIN/comp90024-2025-35"
    branch: "main"
    subpath: "backend/database"  
  buildcmd: |
    pip install --no-cache-dir -r requirements.txt

