include:
- minutely.zip
kind: ArchiveUploadSpec
name: minutely-zip-tpDU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: minutely
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://minutely-zip-tpDU
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T17:47:53Z"
