include:
- timestats.zip
kind: ArchiveUploadSpec
name: timestats-zip-n5yn

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: timestats
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://timestats-zip-n5yn
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T10:56:59Z"
