include:
- mharvest.zip
kind: ArchiveUploadSpec
name: mharvest-zip-KZga

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mharvest
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://mharvest-zip-KZga
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-07T06:38:21Z"
