include:
- mstats.zip
kind: ArchiveUploadSpec
name: mstats-zip-SE86

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mstats
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://mstats-zip-SE86
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T09:15:24Z"
