include:
- demo.zip
kind: ArchiveUploadSpec
name: demo-zip-Mv1G

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: demo
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://demo-zip-Mv1G
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-12T13:28:08Z"
