include:
- rharvest.zip
kind: ArchiveUploadSpec
name: rharvest-zip-JgN8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: rharvest
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://rharvest-zip-JgN8
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-08T04:54:41Z"
