include:
- subredditstats.zip
kind: ArchiveUploadSpec
name: subredditstats-zip-YTet

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: subredditstats
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://subredditstats-zip-YTet
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-16T11:46:25Z"
