include:
- mcontent.zip
kind: ArchiveUploadSpec
name: mcontent-zip-biDe

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mcontent
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://mcontent-zip-biDe
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-17T13:07:06Z"
