apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: stats-mastodon-date-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: mstats
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/mastodon/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/end/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /analysis/mastodon/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/end/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}
