apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: subredditstats
spec:
  createingress: false
  functionref:
    functionweights: null
    name: subredditstats
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /subreddit/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/to/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /subreddit/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/to/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}
