apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: stats-reddit-header-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: rstats
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/reddit
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /analysis/reddit
