apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: stats-reddit-date-keyword-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: rstats
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/reddit/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/end/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}/keyword/{keyword:[A-Za-z0-9_-]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /analysis/reddit/date/{start:[0-9]{4}-[0-9]{2}-[0-9]{2}}/end/{end:[0-9]{4}-[0-9]{2}-[0-9]{2}}/keyword/{keyword:[A-Za-z0-9_-]+}
