apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: demo-date
spec:
  createingress: false
  functionref:
    functionweights: null
    name: demo
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/date/{date:[0-9]{4}-[0-9]{2}-[0-9]{2}}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /analysis/date/{date:[0-9]{4}-[0-9]{2}-[0-9]{2}}
